#!/bin/sh
#
# @name SDU Drone
#
# @type Hexarotor x
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=windy}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=sdu_drone}


set MAV_TYPE 13
set MIXER hexa_x_sdu


param set-default SIM_GZ_EN 1
param set-default CA_ROTOR_COUNT 6

# Hexa-X rotor positions and directions (CA_ROTORx_PX/PY/KM)
param set-default CA_ROTOR0_PX 0.0
param set-default CA_ROTOR0_PY -0.37
param set-default CA_ROTOR0_KM 0.06   # CW

param set-default CA_ROTOR1_PX 0.0
param set-default CA_ROTOR1_PY 0.37
param set-default CA_ROTOR1_KM -0.06  # CCW

param set-default CA_ROTOR2_PX 0.320429
param set-default CA_ROTOR2_PY 0.185
param set-default CA_ROTOR2_KM 0.06   # CW

param set-default CA_ROTOR3_PX -0.320429
param set-default CA_ROTOR3_PY -0.185
param set-default CA_ROTOR3_KM -0.06  # CCW

param set-default CA_ROTOR4_PX 0.320429
param set-default CA_ROTOR4_PY -0.185
param set-default CA_ROTOR4_KM 0.06   # CW

param set-default CA_ROTOR5_PX -0.320429
param set-default CA_ROTOR5_PY 0.185
param set-default CA_ROTOR5_KM -0.06  # CCW



# Gazebo motor assignments
param set-default SIM_GZ_EC_FUNC1 102
param set-default SIM_GZ_EC_FUNC2 103
param set-default SIM_GZ_EC_FUNC3 105
param set-default SIM_GZ_EC_FUNC4 101
param set-default SIM_GZ_EC_FUNC5 104
param set-default SIM_GZ_EC_FUNC6 106

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MIN5 150
param set-default SIM_GZ_EC_MIN6 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000
param set-default SIM_GZ_EC_MAX5 1000
param set-default SIM_GZ_EC_MAX6 1000

# Safety
param set-default NAV_DLL_ACT 0
param set-default NAV_RCL_ACT 0
param set-default COM_DISARM_PRFLT 0
param set-default EKF2_EV_DELAY 50


