#!/bin/sh
#
# @name SDU Drone
#
# @type Hexarotor x
#

. ${R}etc/init.d/rc.mc_defaults


PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}

set MAV_TYPE 13
set MIXER hexa_x_sdu

param set NAV_DLL_ACT 0
param set NAV_RCL_ACT 0
param set COM_OBL_ACT 0

param set EKF2_AID_MASK 1
param set EKF2_HGT_MODE 0
param set EKF2_EV_DELAY 50
